version: '3'

services:
  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "3000:3000" 
      networks:
        - application 
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" 
    networks:
      - application 
networks: 
  application: 
    driver: bridge